platform :ios, '7.0'

pod 'SWTableViewCell', :git => 'https://github.com/CEWendel/SWTableViewCell.git'
pod 'MYBlurIntroductionView', :git => 'git@github.com:MatthewYork/MYBlurIntroductionView.git'
pod 'XYPieChart'
pod 'CRToast'
pod 'TPKeyboardAvoiding'
pod 'EDColor'
pod 'DejalActivityView'
pod 'SparkInspector'
